### ISSUE TITLE
Check 2.4: look in ALL tables PERSONS

### ISSUE THREAD

**Issue by clobart** [UMC-Utrecht-RWE/ConcePTION-Level2#2]
Lookin at the level results, we recognized that in the 2.4 you're looking at ONLY ONE table called exactly PERSONS.csv, while we have two PERSONS tables, and the check needs to look at all the tables that START with PERSONS.

![Immagine](https://user-images.githubusercontent.com/38613747/179242326-f208db71-e923-4d7e-a5fc-c3fa1fddf7cd.png)

**Comment by anallg** [comment]
Same issue in BIFAP - AEMPS. We have 5 person tables, 5 observation periods and 5 visit_occurrence.

**Comment by t-andresvaz** [comment]
Please, download the latest release 2.2 to fix this error.
[Level 2 Version2.1](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level2/releases/tag/Version2.1
)
