### ISSUE TITLE
Report 2.5 error

### ISSUE THREAD

**Issue by clobart** [UMC-Utrecht-RWE/ConcePTION-Level2#5]
I run again all level2, and this time I had an error in report 2.5 

![image](https://user-images.githubusercontent.com/38613747/179922152-7e702e49-69cd-4884-bf10-ee9cb745d92e.png)

The script entered in debug mode. This hasn't happened last time...
What should I do?

@t-andresvaz @acidroyo-UMCU @relbersumcu

**Comment by acidroyo-UMCU** [comment]
Hello @clobart, since the code did not change, did you change anything in the server's environment? What changes did you apply to your database before applying the level2 again?

**Comment by clobart** [comment]
Hi LAbert, I found the error with Roel.. it was a stupid mistake! Thanks for the support, you can close the issue :)
