### ISSUE TITLE
Check 2.5: Error in forderv

### ISSUE THREAD

**Issue by benjamin-johannesen** [UMC-Utrecht-RWE/ConcePTION-Level2#8]
I got the following error message after running just check 2.5 (i.e. line 1-20 and line 26 of "to_run.R") for about one day:

Quitting from lines 33-37 (Report_2_5.Rmd)
Error in forderv(x, by = xcols) : Failed to alloc cradix_tmp

Any ideas what went wrong? This is not the version of the of scripts released a month ago.

**Comment by t-andresvaz** [comment]
hello @benjamin-johannesen 

are you using [this](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level2/releases/tag/Version2.1) version?

**Comment by benjamin-johannesen** [comment]
@t-andresvaz 
I am not. I am using the previous version.

**Comment by t-andresvaz** [comment]
Closed, with no fix.
