### ISSUE TITLE
Run out of RAM

### ISSUE THREAD

**Issue by frasansa** [UMC-Utrecht-RWE/ConcePTION-Level2#9]
Dear @t-andresvaz @relbersumcu,

This issue is already opened for **_level 1_** check.

We are doing the QC for VID datasource for consign and we have some issues with the RAM that are causing:

In **_level 1 check_** the EVENTS folder is empty.
In **_level 2 check_** the MEDICINES and VACCINES are unable to perform check in most of the reports.
There are some strategy to follow for fixing this (splitting some tables by year or similar)?
Thank you in advance,
Francisco

**Comment by t-andresvaz** [comment]
Yes sure. You can split tables by year or other values . Ideal size for each generate files in less than 1 Gb each . Please, for exempla follow this name convention keeping the original name of the table at the beginning :

EVENTS_1.csv 
EVENTS_2.csv
...
EVENTS_10.csv

**Comment by frasansa** [comment]
Thank you!
